### ISSUE TITLE
Can't build with go 1.12

### ISSUE THREAD

**Issue by DeadNumbers** [Quasilyte/concat#2]
`vendor/github.com/Quasilyte/concat.Strings: relocation target runtime.mallocgc not defined for ABI0 (but is defined for ABIInternal)`

**Comment by quasilyte** [comment]
I'll take a look.

**Comment by quasilyte** [comment]
I believe https://github.com/golang/go/commit/685aca45dc8435df7b7e8059a42a8a98efdaf22c is the reason (https://github.com/golang/go/issues/27539).

Not 100% sure how to fix build now, since runtime symbols are part of the internal ABI.

**Comment by quasilyte** [comment]
It could be possible to try something that is described in http://www.alangpierce.com/blog/2016/03/17/adventures-in-go-accessing-unexported-functions/ if it still works, but the better option is to:
1. Stick to non-assembly version. I can probably disable asm amd64 version for go1.12 and above targets.
2. Don't use `concat` as a library.

I wonder, do you really have a need for such thing as a library? :)
